# Generated by Django 5.0.4 on 2024-04-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_parent_urlmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='slug',
            field=models.SlugField(max_length=15, unique=True, verbose_name='Фрагмент url-адреса'),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='url',
            field=models.CharField(max_length=199, unique=True, verbose_name='Полный url-адрес'),
        ),
    ]
