# Generated by Django 5.0.4 on 2024-04-23 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_urlmodel_slug_alter_urlmodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='url',
            field=models.CharField(max_length=199, unique=True, validators=[django.core.validators.RegexValidator(message='Url not valid', regex='^[a-z0-9]+/?[a-z0-9]+/$')], verbose_name='Полный url-адрес'),
        ),
    ]
